FROM docker.io/prom/prometheus:v3.13.1@sha256:3c42b892cf723fa54d2f262c37a0e1f80aa8c8ddb1da7b9b0df9455a35a7f893

USER nobody

# data from ~ 2025-05-26 11:00 to 2025-05-26 12:05
COPY e2e/provisioning/prometheus/data.zip /prometheus/data.zip
RUN unzip /prometheus/data.zip 
RUN rm /prometheus/data.zip 

COPY e2e/provisioning/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
